//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStationRemake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public Bus()
        {
            this.Reis = new HashSet<Reis>();
        }
    
        public int id { get; set; }
        public string registr_number { get; set; }
        public int bort_number { get; set; }
        public string marka { get; set; }
        public int chislo_mestt { get; set; }
        public string voditel { get; set; }
    
        public virtual ICollection<Reis> Reis { get; set; }
    }
}
