//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStationRemake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marshrut
    {
        public Marshrut()
        {
            this.Station_from_marshrut = new HashSet<Station_from_marshrut>();
            this.Reis = new HashSet<Reis>();
        }
    
        public int id { get; set; }
        public decimal bilet_price { get; set; }
        public string destination { get; set; }
    
        public virtual ICollection<Station_from_marshrut> Station_from_marshrut { get; set; }
        public virtual ICollection<Reis> Reis { get; set; }
    }
}
