//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStationRemake
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusStationEntities : DbContext
    {
        public BusStationEntities()
            : base("name=BusStationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bus> Bus { get; set; }
        public DbSet<Marshrut> Marshrut { get; set; }
        public DbSet<Reis> Reis { get; set; }
        public DbSet<Station> Station { get; set; }
        public DbSet<Station_from_marshrut> Station_from_marshrut { get; set; }
    }
}
