//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStationRemake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reis
    {
        public int id { get; set; }
        public int id_marshruta { get; set; }
        public int id_bus { get; set; }
        public System.TimeSpan vremya_opravleniya { get; set; }
        public System.TimeSpan vremya_pribitiya { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Marshrut Marshrut { get; set; }
    }
}
