//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStationRemake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station_from_marshrut
    {
        public int id { get; set; }
        public int id_stancii { get; set; }
        public int id_marshruta { get; set; }
        public System.TimeSpan vremya_otpravleniya { get; set; }
    
        public virtual Marshrut Marshrut { get; set; }
        public virtual Station Station { get; set; }
    }
}
