//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusStationRemake
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Station_from_marshrut = new HashSet<Station_from_marshrut>();
        }
    
        public int id { get; set; }
        public double km_ot_omska { get; set; }
        public string station_name { get; set; }
    
        public virtual ICollection<Station_from_marshrut> Station_from_marshrut { get; set; }
    }
}
